
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (1, 'C.A.S.A UNIMNUTO');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (2, 'Registro');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (3, 'Carnetización');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (4, 'Bibioteca');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (5, 'CAL(Centro de Apoyo Logistico)');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (6, 'Graduados');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (7, 'Oficina de Asuntos Internacionales');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (8, 'Posgrados');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (9, 'Deportes');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (10, 'Centro progresa');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (11, 'Salud');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (12, 'Recepción Facultad de Ciencias Empresariales');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (13, 'Recepción Facultad de ingenieria');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (14, 'Recepción Facultad de educacion');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (15, 'Ciencias humanas y sociales');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (16, 'Ciencias de la comunicación');
INSERT INTO areas (PK_IN_ID_AREA, VAR_DESCRIPCION_AREA) 
VALUES (17, 'Recepción UNIMINUTO');


INSERT INTO usuarios (pk_in_id_user, var_username, var_contrasena)
VALUES (1, 'admin', 'admin');


INSERT INTO registros (PK_IN_ID_REGISTRO, IN_NIVEL_SATISFACCIONI, AREAS_PK_IN_ID_AREA, TIM_FECHA_REGISTRO)
VALUES (1,98, 1, SYSDATE);
INSERT INTO registros (PK_IN_ID_REGISTRO, IN_NIVEL_SATISFACCIONI, AREAS_PK_IN_ID_AREA, TIM_FECHA_REGISTRO)
VALUES (2,90, 2, SYSDATE);
INSERT INTO registros (PK_IN_ID_REGISTRO, IN_NIVEL_SATISFACCIONI, AREAS_PK_IN_ID_AREA, TIM_FECHA_REGISTRO)
VALUES (3,70, 3, SYSDATE);
INSERT INTO registros (PK_IN_ID_REGISTRO, IN_NIVEL_SATISFACCIONI, AREAS_PK_IN_ID_AREA, TIM_FECHA_REGISTRO)
VALUES (4,45, 4, SYSDATE);
INSERT INTO registros (PK_IN_ID_REGISTRO, IN_NIVEL_SATISFACCIONI, AREAS_PK_IN_ID_AREA, TIM_FECHA_REGISTRO)
VALUES (5, 70, 5, SYSDATE);